### ISSUE TITLE
[Feature]: Backup Password Option

### ISSUE THREAD

**Issue by lewislarsen** [vanguardbackup/vanguard#11]
### Feature Title

Add option for encrypted backups

### Feature Description

When creating a backup task, there should be an option to type in a password that encrypts the backup for security.

### Vanguard Version

v1.4.1

**Comment by danilovict2** [comment]
Hi, can you explain what you mean by "a password that encrypts the backup". Thanks

**Comment by lewislarsen** [comment]
> Hi, can you explain what you mean by "a password that encrypts the backup". Thanks

Hey, sure!

What I think would be cool is that during the backup process, if a password is supplied it will encrypt the file and use the supplied password as the password needed to decrypt it.

Not too sure when I'll get around to adding it, but it doesn't seem difficult to do. :)
